@extends('layouts.standard')

@section('content')
    <div class="container">
        <h1>I am example</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed magna tincidunt, euismod leo lacinia, mollis metus. Proin in quam nunc. In vel felis semper, lacinia turpis nec, congue risus. Curabitur sed suscipit velit, eget pulvinar ligula. Quisque a luctus dui. In hac habitasse platea dictumst. Aliquam luctus pulvinar commodo. Quisque imperdiet nunc leo, eu consequat ante auctor ut. Curabitur tincidunt, ipsum scelerisque tincidunt maximus, lorem metus maximus odio, quis porta nunc risus ut lectus. Vivamus vel feugiat diam. Mauris arcu urna, laoreet eget tellus at, elementum auctor elit. Praesent dignissim fermentum sem sed dignissim.</p>
        <p>Cras vitae mauris posuere, varius ligula ultricies, interdum elit. Curabitur viverra tincidunt lacus. Maecenas efficitur faucibus dui, sit amet tempor sem pretium ut. Pellentesque eu mattis sem. Mauris convallis id orci blandit ultricies. Morbi interdum elit lectus, vel auctor libero tempus id. Nullam mollis eros non quam mattis, vitae finibus nisl accumsan. Nam molestie nisl eleifend nibh faucibus, vitae accumsan lorem iaculis. Aliquam tincidunt augue a mi commodo hendrerit. Morbi venenatis imperdiet tellus, in laoreet ante molestie tincidunt. Cras magna tellus, mattis non nisl ac, porttitor facilisis est. Vivamus ac faucibus arcu, non blandit eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce a molestie tortor.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend nunc ut magna posuere varius. Nunc scelerisque at ex vitae feugiat. Aliquam quis erat non erat dictum varius. Mauris at tellus pretium, tincidunt sem eu, aliquam purus. Quisque id tortor eget lacus euismod efficitur. Aliquam quis auctor nulla. Maecenas vel commodo justo, mollis semper turpis. Mauris eget urna ut tortor elementum rutrum. Sed mattis fringilla augue, et mollis elit pulvinar quis. Nulla tellus ipsum, facilisis in magna ut, facilisis hendrerit lectus. Praesent tempor tempus mi ut sagittis. Suspendisse ex magna, euismod vitae diam in, suscipit mattis nibh. Sed eu euismod enim.</p>
    </div>
@endsection
